submission:
	tar cvzf cs155_proj3_submission.tar.gz \
	  --exclude-backups --exclude=client.py --exclude=fileToDownload.txt \
	  --exclude=dnsServer.py --exclude=httpServer.py --exclude=run.sh \
	  --exclude=stop.sh --exclude=reset.sh --exclude=trace.txt \
	  part1/ part2/ part3/ part4/
